# thi is a basic workflow to help you get started with github

name: ci

# control when the workflow will run
on:

  # trigger the workflow on push or pull request but only on main branch
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

  # allow you to run the workflow manually from action tab 
  workflow_dispatch:

# a workflow run is made of job that run parallel or sequential
jobs:
  # this workflow contain a single job called "build"
  build-and-release:
    # this a type of runner that the job would run 
    runs-on: ubuntu-latest

    # sequence represent a list of task that would be run as part of job
    steps:
      # check_out your workspace under GITHUB_workspace, so as job can access it 
      - uses: actions/checkout@v3

      # run a single line command using runner shell
      - name: Run a one-line script
        run: echo hello, world!
      
      # run a set of command using runner shell
      - name: run a multi-line script
        run: |
          echo "Add action other action to build,"
          echo "test and the deploy your project."

     

  
